apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue-deployment
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: vue
  template:
    metadata:
      labels:
        app: vue
    spec:
      containers:
        - name: vue-container
          image: sinwookim/frontend:39
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: BACKEND_URL
              value: "http://boot-service:8001"
---
apiVersion: v1
kind: Service
metadata:
  name: vue-service
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 80
  selector:
    app: vue