spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: ${DB_URL:jdbc:mariadb://localhost:3306/account_book?useUnicode=true&characterEncoding=UTF-8}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:mariadb}
    driver-class-name: org.mariadb.jdbc.Driver

jwt:
  secret: ${JWT_SECRET:MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=}
  expiration: ${JWT_EXPIRATION:86400000}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000}
